config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  root to: "public/homes#top"
  
  namespace :public do
    get '/about', to: "homes#about", as: 'about'
    resources :items, only: [:show, :index ]

    resource :customer, only: [:show]
    get '/information/edit', to: 'customers#edit', as: 'edit_customer'
    patch '/information/update', to: 'customers#update', as: 'update_customer'
    get '/confirmation', to: "customers#confirmation", as: 'customers_confirmation'
    patch '/withdrawal', to: 'customers#withdrawal', as: 'customers_withdrawal'


    resources :cart_items, only: [:index, :update, :destroy, :create] do
    collection do
    delete :destroy_all
    end
  end
    resources :orders, only: [:new, :index, :show, :create ]
    post '/confirm', to: 'orders#confirm', as: 'orders_confirm'
    get '/complete', to: 'orders#complete', as: 'orders_complete'

  end

  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update ]
    resources :customers, only: [:index, :show, :edit, :update ]
    resources :orders, only: [:show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :items
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def subtotal
  item.with_tax_price * quantity
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :addresses

  def full_name
    "#{last_name} #{first_name}"
  end
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  
  has_one_attached :image
  has_many :cart_items
  
  def with_tax_price
  (price * 1.1).floor
  end
  
   def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
   end 

end 

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  belongs_to :customer
  has_many :order_details
  
  before_validation :set_default_payment_method

  private

  def set_default_payment_method
    self.payment_method ||= :credit_card if self.payment_method.blank?
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  def subtotal
    quantity * item.with_tax_price
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end 
  
  def show
    @customer = Customer.find(params[:id])
  end 
  
  def edit
    @customer = Customer.find(params[:id])
  end 
  
  def update
  @customer = Customer.find(params[:id])

  if @customer.update(customer_params)
    redirect_to admin_customer_path(@customer), notice: "会員情報が更新されました。"
  else
    render :edit
  end
  end

private

def customer_params
  params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted )
end

  
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
     @orders = Order.order(created_at: :desc).page(params[:page])
  end   
    
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    
    if @item.save
      redirect_to admin_item_path(@item), notice: "商品を登録しました。"
    else
      render :new
    end
  end
  
  def index
    @items = Item.page(params[:page])
    
  end 
  
  def show
    @item = Item.find(params[:id])
  end 
  
  def edit
    @item = Item.find(params[:id])
  end
  
  
  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: "商品情報が更新されました。"
    else
      render :edit
    end
  end


  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @payment_method_display = @order.payment_method == 'credit_card' ? 'クレジットカード' : '銀行振込'
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
    
    
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
   protected

  # ログアウト後のリダイレクト先を設定
  def after_sign_out_path_for(resource_or_scope)
    new_admin_session_path  # 管理者ログイン画面へのパスに変更する
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?
   
 
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  

end

app/helpers/adimin/orders_helper.rb
module Adimin::OrdersHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container ">
<h2><%= "#{@customer.last_name} #{@customer.first_name}" %>さんの会員編集</h2>

<%= form_with(model: @customer, url: admin_customer_path(@customer), local: true) do |f| %>
 <div class="field d-flex">
  <%= f.label :last_name, '氏名', class: 'mr-3' %>
  <%= f.text_field :last_name, class: 'mr-2' %>
  <%= f.text_field :first_name, class: 'mr-2' %>
 </div>
 
 <div class="field d-flex mt-3">
    <%= f.label :first_name_kana, 'ふりがな', class: 'mr-3 ' %>
    <%= f.text_field :last_name_kana, class: 'mr-2' %>
    <%= f.text_field :first_name_kana, class: 'mr-2' %>
  </div>

  <div class="field ">
    <%= f.label :postal_code, '郵便番号', class: 'mr-3 mt-3' %>
    <%= f.text_field :postal_code %>
  </div>

  <div class="field mt-3">
    <%= f.label :address, '住所', class: 'mr-2' %>
    <%= f.text_area :address %>
  </div>

  <div class="field">
    <%= f.label :telephone_number, '電話番号', class: 'mr-2' %>
    <%= f.text_field :telephone_number %>
  </div>

  <div class="field">
    <%= f.label :email, 'メールアドレス', class: 'mr-2' %>
    <%= f.text_field :email %>
  </div>
  
 <div class="field d-flex">
  <%= f.label :is_deleted, '会員ステータス', class: 'mr-3' %>
  <div class="form-check mr-2">
    <%= f.radio_button :is_deleted, false, class: 'form-check-input' %>
    <%= f.label :is_deleted, '有効', class: 'form-check-label' %>
  </div>
  <div class="form-check">
    <%= f.radio_button :is_deleted, true, class: 'form-check-input' %>
    <%= f.label :is_deleted, '退会', class: 'form-check-label' %>
  </div>
</div>


  <%= f.submit '更新する', class: 'btn btn-primary' %>
<% end %>

app/views/admin/customers/index.html.erb
<div class="container text-center">
  <div class="text-left">
    <h2>会員一覧</h2>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
         <td class="text-center">
          <%= link_to "#{customer.last_name} #{customer.first_name}", admin_customer_path(customer) %>
         </td>
          <td class="text-center"><%= customer.email %></td>
      <td class="text-center">
        <% if customer.is_deleted %>
          <span class="text-danger">退会</span>
        <% else %>
          <span class="text-success">有効</span>
        <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <h2><%= "#{@customer.last_name} #{@customer.first_name}" %>さんの会員詳細</h2>

  <p><strong>会員ID:</strong> <%= @customer.id %></p>
  <p><strong>氏名:</strong> <%= "#{@customer.last_name} #{@customer.first_name}" %></p>
  <p><strong>ふりがな:</strong> <%= "#{@customer.last_name_kana} #{@customer.first_name_kana}" %></p>
  <p><strong>郵便番号:</strong> <%= @customer.postal_code %></p>
  <p><strong>住所:</strong> <%= @customer.address %></p>
  <p><strong>電話番号:</strong> <%= @customer.telephone_number %></p>
  <p><strong>メールアドレス:</strong> <%= @customer.email %></p>
  <p><strong>ステータス:</strong> <%= @customer.is_deleted ? '退会' : '有効' %></p>
  
  <div class="mt-3">
    <%= link_to '編集', edit_admin_customer_path(@customer), class: 'btn btn-primary' %>
    <%= link_to '注文履歴一覧', admin_root_path(customer_id: @customer.id), class: 'btn btn-success ml-2' %>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h2 class="text-center">商品編集</h2>
        </div>

        <%= form_with(model: @item, url: admin_item_path(@item), method: :patch, local: true) do |f| %>
          <div class="card-body">
            <div class="form-group row">
              <div class="col-sm-4">
                <%= f.label :image, "商品画像" %>
              </div>
              <div class="col-sm-8">
                <%= f.file_field :image, class: "form-control" %>
              </div>
            </div>

            <div class="form-group row">
              <div class="col-sm-4">
                <%= f.label :name, "商品名" %>
              </div>
              <div class="col-sm-8">
                <%= f.text_field :name, class: "form-control" %>
              </div>
            </div>

            <div class="form-group row">
              <div class="col-sm-4">
                <%= f.label :introduction, "商品説明" %>
              </div>
              <div class="col-sm-8">
                <%= f.text_area :introduction, class: "form-control" %>
              </div>
            </div>

            <div class="form-group row">
              <div class="col-sm-4">
                <%= f.label :price, "税抜価格" %>
              </div>
              <div class="col-sm-8 d-flex align-items-center">
                <%= f.number_field :price, class: "form-control" %>
                <span class="ml-2">円</span>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "変更を保存", class: "btn btn-success" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container mt-5">
  <div class="row justify-content-between mb-3">
    <div class="col-md-6">
      <h2>商品一覧</h2>
    </div>
    <div class="col-md-2 text-right">
      <%= link_to "＋", new_admin_item_path, class: "btn btn-primary" %>
    </div>
  </div>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>価格</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to item.name, admin_item_path(item) %></td>
          <td><%= item.price %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <%= paginate @items %>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h2 class="text-center">商品新規登録</h2>
        </div>
        <div class="card-body">
          <%= form_with(model: @item, url: admin_items_path, local: true) do |f| %>
            <div class="card-body">
            <div class="form-group row">
              <div class="col-sm-4">
                <%= f.label :image, "商品画像" %>
              </div>
              <div class="col-sm-8">
                <%= f.file_field :image, class: "form-control" %>
              </div>
            </div>

            <div class="form-group row">
              <div class="col-sm-4">
                <%= f.label :name, "商品名" %>
              </div>
              <div class="col-sm-8">
                <%= f.text_field :name, class: "form-control" %>
              </div>
            </div>

            <div class="form-group row">
              <div class="col-sm-4">
                <%= f.label :introduction, "商品説明" %>
              </div>
              <div class="col-sm-8">
                <%= f.text_area :introduction, class: "form-control" %>
              </div>
            </div>

            <div class="form-group row">
              <div class="col-sm-4">
                <%= f.label :price, "税抜価格" %>
              </div>
              <div class="col-sm-8 d-flex align-items-center">
                <%= f.number_field :price, class: "form-control" %>
                <span class="ml-2">円</span>
              </div>
            </div>
            <div class="text-center">
              <%= f.submit "新規登録", class: "btn btn-success" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<% if @item.errors.any? %>
  <div class="alert alert-danger">
    <h4><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h4>
    <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/items/show.html.erb
<div class="container mt-5">
  <h2>商品詳細</h2>
  <div class="row">
    <div class="col-md-4">
      
      <% if @item.image.attached? %>
        <%= image_tag @item.image, class: "img-fluid rounded" %>
      <% else %>
        <p>画像がありません</p>
      <% end %>
    </div>
    <div class="col-md-8">
      <p><strong>商品名:</strong> <%= @item.name %></p>
      <p><strong>説明:</strong> <%= @item.introduction %></p>
      <p>
        <strong>税込価格（税抜価格）</strong>
        <%= (@item.price * 1.1).floor %>( <%= @item.price %> )円
      </p>
       <%= link_to '編集する', edit_admin_item_path(@item), class: 'btn btn-success' %>
    </div>
  </div>
</div>

<style>
  .small-image {
    max-width: 200px; /* 任意のサイズに調整 */
  }
</style>