config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  root to: "public/homes#top"
  
  namespace :public do
    get '/about', to: "homes#about", as: 'about'
    resources :items, only: [:show, :index ]

    resource :customer, only: [:show]
    get '/information/edit', to: 'customers#edit', as: 'edit_customer'
    patch '/information/update', to: 'customers#update', as: 'update_customer'
    get '/confirmation', to: "customers#confirmation", as: 'customers_confirmation'
    patch '/withdrawal', to: 'customers#withdrawal', as: 'customers_withdrawal'


    resources :cart_items, only: [:index, :update, :destroy, :create] do
    collection do
    delete :destroy_all
    end
  end
    resources :orders, only: [:new, :index, :show, :create ]
    post '/confirm', to: 'orders#confirm', as: 'orders_confirm'
    get '/complete', to: 'orders#complete', as: 'orders_complete'

  end

  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update ]
    resources :customers, only: [:index, :show, :edit, :update ]
    resources :orders, only: [:show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  belongs_to :customer
  has_many :order_details
  
  before_validation :set_default_payment_method

  private

  def set_default_payment_method
    self.payment_method ||= :credit_card if self.payment_method.blank?
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @payment_method_display = @order.payment_method == 'credit_card' ? 'クレジットカード' : '銀行振込'
  end
end

app/helpers/adimin/orders_helper.rb
module Adimin::OrdersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <h1>管理者側注文詳細</h1>
  
      <p>注文ID: <%= @order.id %></p>
      <p>購入日時: <%= @order.created_at %></p>
      <p><strong>購入者:</strong> <%= link_to @order.customer.full_name, admin_customer_path(@order.customer) %></p>
      <p><strong>配送先住所:</strong> <%= @order.shipping_address %></p>
      <p><strong>支払い方法:</strong> <%= @payment_method_display %></p>
      
  <div class="row">
    <div class="col-md-6">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>商品名</th>
            <th>価格</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |detail| %>
            <tr>
              <td><%= detail.item.name %></td>
              <td><%= detail.item.with_tax_price %></td>
              <td><%= detail.quantity %></td>
              <td><%= detail.subtotal %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    
    <div class="col-md-6 offset-md-6">
        <p><strong>商品合計:</strong> <%= @order.order_details.sum { |detail| detail.item.with_tax_price * detail.quantity } %> 円 </p>
        <p><strong>送料:</strong> <%= @order.shipping_fee %>円</p>
        <p><strong>請求金額合計:</strong> <%= @order.order_details.sum { |detail| detail.item.with_tax_price * detail.quantity } + @order.shipping_fee %>円</p>
    </div>
  </div>
</div>