config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  root to: "public/homes#top"
  
  namespace :public do
    get '/about', to: "homes#about", as: 'about'
    resources :items, only: [:show, :index ]

    resource :customer, only: [:show]
    get '/information/edit', to: 'customers#edit', as: 'edit_customer'
    patch '/information/update', to: 'customers#update', as: 'update_customer'
    get '/confirmation', to: "customers#confirmation", as: 'customers_confirmation'
    patch '/withdrawal', to: 'customers#withdrawal', as: 'customers_withdrawal'


    resources :cart_items, only: [:index, :update, :destroy, :create] do
    collection do
    delete :destroy_all
    end
  end
    resources :orders, only: [:new, :index, :show, :create ]
    post '/confirm', to: 'orders#confirm', as: 'orders_confirm'
    get '/complete', to: 'orders#complete', as: 'orders_complete'

  end

  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update ]
    resources :customers, only: [:index, :show, :edit, :update ]
    resources :orders, only: [:show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :items
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def subtotal
  item.with_tax_price * quantity
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :addresses

  def full_name
    "#{last_name} #{first_name}"
  end
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  
  has_one_attached :image
  has_many :cart_items
  
  def with_tax_price
  (price * 1.1).floor
  end
  
   def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
   end 

end 

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  belongs_to :customer
  has_many :order_details
  
  before_validation :set_default_payment_method

  private

  def set_default_payment_method
    self.payment_method ||= :credit_card if self.payment_method.blank?
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  def subtotal
    quantity * item.with_tax_price
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
     @orders = Order.order(created_at: :desc).page(params[:page])
  end   
    
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    
    if @item.save
      redirect_to admin_item_path(@item), notice: "商品を登録しました。"
    else
      render :new
    end
  end
  
  def index
    @items = Item.page(params[:page])
    
  end 
  
  def show
    @item = Item.find(params[:id])
  end 
  
  def edit
    @item = Item.find(params[:id])
  end
  
  
  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: "商品情報が更新されました。"
    else
      render :edit
    end
  end


  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @payment_method_display = @order.payment_method == 'credit_card' ? 'クレジットカード' : '銀行振込'
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?
   
 
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  

end

app/helpers/adimin/orders_helper.rb
module Adimin::OrdersHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br/>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- BootstrapのCSSを読み込む -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Bootstrapのナビゲーションバーを使用 -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <!-- ロゴを左側に表示 -->
    <a class="navbar-brand" href="<%= root_path %>">NaganoCake</a>

    <!-- メニュー項目を左側に寄せるための調整 -->
    <div class="navbar-collapse justify-content-start" id="navbarNav">
      <ul class="navbar-nav">
            <% if admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "商品一覧", admin_items_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "会員一覧", admin_customers_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "注文履歴一覧", admin_root_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% elsif customer_signed_in? %>
              <li class="nav-item">
                <%= link_to "マイページ", public_customer_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "商品一覧", public_items_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "カート", public_cart_items_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "about", public_about_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "商品一覧", public_items_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_customer_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_customer_session_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>

    <!-- BootstrapのJavaScriptを読み込む -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>